### ISSUE TITLE
Port Emilie's pKa Java code into Python 

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#62] opened 2014-04-22 16:41 UTC

**Comment by lizutah** [comment] 2015-05-22 16:09
duplicate of #230, closing.

**Comment by lizutah** [comment] 2015-05-26 17:10
Clarifying this issue:  This is the coversion of Emilie's command line version of the graph cut code into python.

**Comment by lizutah** [comment] 2015-08-18 22:25
close?

**Comment by kmonson** [comment] 2015-08-19 00:52
Not yet, working through a few issues.

**Comment by kmonson** [comment] 2015-09-04 17:51
We'll close this and track any remaining issues in the issues for https://github.com/Electrostatics/graphcut

**Closed by kmonson** 2015-09-04 17:51 UTC
Labels: enhancement, pdb2pqr
