### ISSUE TITLE
Profile and accelerate geometric flow solver

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#220] opened 2015-05-19 19:17 UTC
Probably best to fix #219 first.

**Comment by sobolevnrm** [comment] 2015-05-19 19:32
Could be useful for #225 -- issue #225 should probably come first.

**Comment by keith923** [comment] 2015-06-22 22:05
Is this a dupe of #235?

**Comment by lizutah** [comment] 2015-06-23 00:47
Yes, if we think we've done all the acceleration necessary. Maybe other acceleration steps need to go in a separate issue?

**Comment by lizutah** [comment] 2015-06-29 16:36
Closing since this is a duplicate of #235 and #225 should be done before profiling again.

**Closed by lizutah** 2015-06-29 16:36 UTC
Labels: apbs, enhancement, geometric flow
