### ISSUE TITLE
propKa 3.1 as plugin

### ISSUE THREAD

**Issue by lizutah** [Electrostatics/apbs-pdb2pqr#425] opened 2016-01-14 23:17 UTC
fork our own repository, complete with examples

**Comment by sobolevnrm** [comment] 2020-04-19 14:42
https://github.com/jensengroup/propka-3.1

It would be nice to do this after the Python 3 upgrade.

**Comment by sobolevnrm** [comment] 2020-04-19 15:49
Duplicate of #48.

**Closed by sobolevnrm** 2020-04-19 15:49 UTC
