### ISSUE TITLE
APBS error parsing ambPQR files

### ISSUE THREAD

**Issue by keith923** [Electrostatics/apbs-pdb2pqr#214] opened 2015-05-05 01:00 UTC
From a user:

> From: LI An-Bang [mailto:anbangli@qq.com] 
> Sent: Sunday, May 03, 2015 19:04
> To: apbs-users
> Subject: [apbs-users] A bug of APBS in reading PQR file
>  
> Hi, developers of APBS,
>  
> Here I report a bug of APBS in reading PQR file.
>  
> I have some PQR files in ambPQR format. When I run APBS calculation, I got the following error information:
>  
> Parsing input file 4ull.in...
> Parsed input file.
> Got paths for 1 molecules
> Reading PQR-format atom data from 4ull.pqr.
> Valist_readPDB:  Unable to parse serial token (radii) as int!
> Valist_readPDB:  Error while parsing serial!
> Valist_readPDB:  Can't find x!
> Valist_readPQR:  Error parsing atom -1728265984!
>  
> After checking the PQR file, I found that the reason comes from the REMARK lines of the PQR file:
>  
> REMARK  atom radii in columns 55-62
> REMARK  atom charges in columns 63-70
>  
> The lines begin with keyword "REMARK" and follow with word "atom". APBS recognize the lines as  atom information lines with keyword "ATOM". And thus the error occurs. I deleted the "atom" word in the lines and the error disapeared.
>

**Comment by keith923** [comment] 2015-05-05 01:21
The code that reads PQR files is in `valist.c`.  The function is `Valist_readPQR`.  That function only recognizes *ATOM* and *HETATM* keywords.  In other words, it does not know what to do with a '*REMARK* line'.

The user reports that this is an ambPQR file.  I'm not sure of the provenance of the file, and Google doesn't turn up any useful results.

I would recommend that we put this off until we do the PQR file reader for Sphinx -- especially since there is a simple work-around.

**Comment by anbangli** [comment] 2015-05-05 02:00
I am the user who reported the bug.

The PQR files come from Ray Lou's website: http://rayl0.bio.uci.edu/rayl/

There are some database on the website. The PQR files of the "Protein Test Case" are generated by ambPQR. And in these PQR files there are remark lines as follows which trigger the error:

REMARK  PQR file in ambPQR format.
REMARK
REMARK  atom radii in columns 55-62
REMARK  atom charges in columns 63-70

Besides, please check the PDB files of the "Nucleic Acid Test Case". I noticed there are remark lines as follows which may also trigger the error:

 DELPHI PDB FILE
 FORMAT = 2
 HEADER output from qdiff
 HEADER atom radii in columns 55-66
 HEADER atom charges in columns 67-78

This is a simple problem. I recommand that the function Valist_readPQR  should recognizes keywords "ATOM  " (with 2 spaces) and "HETATM" in the beginning of the lines.

**Comment by lizutah** [comment] 2015-05-22 16:04
duplicate of #77 ?

**Comment by kozlac** [comment] 2015-09-10 16:45
I added a new method to maloc's vio.c and made modifications to Valist_readPQR in valist.c in order to handle the issues above. Now, as long as the keywords ATOM or HETATM are the beginning of the line and in the correct section of the file (even with spaces at the beginning) the parsing should work.

**Closed by kozlac** 2015-09-10 16:45 UTC
Labels: apbs, enhancement, intern, pdb2pqr
