### ISSUE TITLE
Geometric flow test suite for APBS

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-pdb2pqr#29] opened 2014-04-04 00:47 UTC
@lizutah

**Comment by lizutah** [comment] 2015-05-22 19:23
duplicate of #224

**Comment by lizutah** [comment] 2015-07-14 17:51
from #224, needs to include small molecules and 1a1p

**Comment by sozenoid** [comment] 2020-06-12 07:17
Hello, 
I think there is still ambiguity in APBS 3.0.0 (that does not output energy units in the geoflow computation) and the definition of the keywords on the website. Are gamma and press given in kcal or kJ? Thank you very much for writing this code. I'm very grateful for it.

**Comment by sobolevnrm** [comment] 2020-06-12 13:09
@sozenoid - thank you for the feedback.  I've created a new issue #606 that focuses on this problem.

**Closed** 2020-06-12 13:10 UTC
Labels: apbs, documentation, geometric flow
